### ISSUE TITLE
ManageDemands com loading eterno

### ISSUE THREAD

**Issue by joaoaugustogrobe** [jefersonralmeida/sospandemia#18]
O widget de loading é carregado de acordo com a existencia ou não de demandas. Quando a requisição termina, demandas deixa de ser um vetor vazio e passa a conter elementos, dessa forma o widget de loading é ocultado e os cards de cada demanda aparecem.
Essa lógica esta fazendo com que entidades sem demandas cadastradas fiquem em um eterno loading (apenas visualmente). 

Corrigir esse comportamento, informando um feedback para o usuario informando que a entidade não possui nenhuma demanda.

**Comment by edsonsilvajr** [comment]
resolvido! Farei o PR de uma branch "solvingEternalLoading"
