### ISSUE TITLE
Validação de formulario - Demandas

### ISSUE THREAD

**Issue by joaoaugustogrobe** [jefersonralmeida/sospandemia#21]
Reescrever formulários de criação e alteração de demandas para fazer a validação dos dados no frontend. Requisitos de cada um dos campos podem ser obtidos pelo banco ou com o @jefersonralmeida. 
A validação deve:
-permitir submissão de dados validos para a API;
-validar resposta da API (obtido em response) em caso de erros ou resposta HTTP diferentes do grupo 200;

Para a validação, recomendo usar as bibliotecas vuelidate ou vuetify.

**Comment by hernanicruz** [comment]
Ciente.

**Comment by hernanicruz** [comment]
Foi utilizado a função vuetfy para validar os campos de input.
