### ISSUE TITLE
Função "Alterar Entidade" quebrada

### ISSUE THREAD

**Issue by edsonsilvajr** [jefersonralmeida/sospandemia#39]
Após o PR #37 a função de alterar entidade deixou de funcionar para os campos de cidade e estado, tendo em vista que a mesmo não funciona da maneira correta, é necessário fazer as alterações necessárias para que esta função volte a funcionar normalmente.
Somente os campos de estado e cidade são o problema, o restante atualiza normalmente.

**Comment by jefersonralmeida** [comment]
Os campos de estado e cidade foram desativados por hora, já que é pouco provável que uma entidade mude de cidade.

Por hora essa issue será movida para a wishlist, e retirada do MVP.

Futuramente podemos utilizar o mesmo esquema de busca de estado/cidade da criação de entidade, para encontrar o id do distrito e enviar na requisição de update da entidade.

**Comment by jefersonralmeida** [comment]
Não é mais um bug, sendo que desabilitamos a alteração por hora.

**Comment by jefersonralmeida** [comment]
Duplicada pela issue #60 , por isso estou fechando essa.
