### ISSUE TITLE
Busca sem resultados não mostra nada

### ISSUE THREAD

**Issue by jefersonralmeida** [jefersonralmeida/sospandemia#51]
Quando o usuário digita um termo que não retorna nada na busca de distritos, nada acontece. Isso pode ser confuso para o usuário.

# Passos para reproduzir:
- Acessar `http://dev.sospandemia.org`
- Clicar em `FILTRO AVANÇADO`
- Selecionar o estado PR
- Digitar a cidade `jagua` (para encontrar jaguariaíva)

# Resultado atual:
![2020-04-10_19h24_37](https://user-images.githubusercontent.com/2734240/79026992-f07ca980-7b60-11ea-82da-37b2df9acfad.png)

# Resultado esperado:
Mostrar na lista uma mensagem do tipo "Nenhuma cidade encontrada. Verifique a busca ou seja mais específico". Da forma que está o usuário pode não entender que se ele continuar digitando a cidade será encontradada.

# Detalhes adicionais
A busca não encontra Jaguariaíva com a busca `jagua`, por conta das configurações do motor de busca. Provavelmente `jagua` não atinge o score necessário para retornar `Jaguariaíva`. Isso pode ser melhorado para a busca poder ser menos específica, mas isso não muda a necessidade dessa mensagem para auxiliar o usuário.

**Comment by joaoaugustogrobe** [comment]
Corrigido em 84512e4dd8759d9df1cef474d2d52d93d04848a5.
