### ISSUE TITLE
Dropdown de estado não funciona quando o foco ocorre por tabulação

### ISSUE THREAD

**Issue by jefersonralmeida** [jefersonralmeida/sospandemia#52]
No cadastro de entidade, se o formulário for preenchido sem utilizar o mouse, no momento que o foco vai para o campo de seleção de estado, e você começa a digitar, funciona o auto-complete, mas não aparece o dropdown.

# Passos para reproduzir
- Entrar no cadastro de nova entidade
- Clicar no campo endereço
- Pressionar tab
- Digitar `P`

# Resultado atual
- Vai aparecer no campo o valor `PA`
- Nenhum dropdown com todos os estados iniciados com `P` aparece.

# Resultado esperado
- Deveria ser igual a quando você clica com o mouse diretamente no campo estado, onde aparece um dropdown com todos os estados.

# Detalhes adicionais
- Tavelz seja interessante seguir o mesmo padrão utilizado no campo cidade, que funciona muito bem.

**Comment by joaoaugustogrobe** [comment]
Esse comportamento atual é o comportamento normal do componente _select_ do HTML ao ganhar foco, como pode ser testado em `https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select`. 
Posso fazer a alteração para um input com autocomplete, mas isso pode piorar a experiencia do usuário mobile.

**Comment by jefersonralmeida** [comment]
Ok. Vamos deixar assim. Não parece ser um grande problema.
