### ISSUE TITLE
Tamanho do campo de Estados em dispositivos mobile

### ISSUE THREAD

**Issue by hernanicruz** [jefersonralmeida/sospandemia#59]
No cadastro de entidade, em dispositivo mobile, o campo de estado fica com tamanho reduzido, e não mostra os dois caracteres do estado.

# Resultado esperado

   Tornar mais fácil para o usuário encontrar o estado

![image](https://user-images.githubusercontent.com/44038950/79142517-03c28b80-7d92-11ea-89ce-485e85bc53cd.png)

**Comment by jefersonralmeida** [comment]
Verificado e já está corrigido. Fechando a issue.
