### ISSUE TITLE
Campo Alterar entidade - Estado cidade desabilitados

### ISSUE THREAD

**Issue by hernanicruz** [jefersonralmeida/sospandemia#60]
Os campos Estado e Cidade, deveria ficar ativo, pois caso o usuário erre apenas a cidade, ele necessitaria exlcuir a entidade e digitalizar dados novamente.

![image](https://user-images.githubusercontent.com/44038950/79143078-f5c13a80-7d92-11ea-825c-882a88d8684f.png)

# Solução
Permitir a alteração da cidade para agilizar os cadastros das entidades.

**Comment by jefersonralmeida** [comment]
@joaoaugustogrobe , seria interessante convertermos esses dois campos num componente/widget, pois eles são usados em conjunto em diversas partes do sistema.

**Comment by jefersonralmeida** [comment]
Selecionado para versão 1.1

**Comment by joaoaugustogrobe** [comment]
Resolvido em f7548758a4857cf061815a91081cf8917bb8ae05
Criado componente para realizar buscas dos distritos de acordo com um estado (passado por prop).
