### ISSUE TITLE
Disponibilizar contato na tela inicial das demandas

### ISSUE THREAD

**Issue by hernanicruz** [jefersonralmeida/sospandemia#82]
# Problema
Não há canal de comunicação entre a unidade que precisa de demanda e quem quer doar.

**Comment by jefersonralmeida** [comment]
Vamos incluir um campo aberto "contato" no cadastro de entidade.
O nome da entidade na listagem de demandas deve virar um link, para uma página que trás todos os detalhes da entidade. Vou providenciar as alterações no backend.

**Comment by jefersonralmeida** [comment]
Incluí um campo contact_form na entidade e na demanda.
@joaoaugustogrobe / @edsonsilvajr precisamos incluir eles nos formulários.

Na exibição da demanda na busca, já está aparecendo (conforme screenshot)

Também é importante, nos resultados da busca, Transformar o nome da entidade em um link, que abra um modal com todas as informações a entidade (inclusive endereço, CNPJ, e nome empresarial. É importante para validação da entidade antes de uma doação.

Também foi incluído no cadastro de demandas um campo unidade, para indicar a unidade da quantidade. é um campo de texto simples. Basta incluir no formulário. Também já está exibindo no resultado da busca...

![2020-04-20_23h06_36](https://user-images.githubusercontent.com/2734240/79817404-d199c680-835b-11ea-9b6d-4d12c9f55e1f.png)


Estou assinando esse ticket para vocês.
