### ISSUE TITLE
Campo de alteração da demanda

### ISSUE THREAD

**Issue by hernanicruz** [jefersonralmeida/sospandemia#83]
# Problema
Um usuário reportou que há itens que necessitam de uma descrição grande. Conforme ele digita, o botão para salvar ou cancelar fica escondido.
![IMG-20200418-WA0047](https://user-images.githubusercontent.com/44038950/79673748-e1c27200-81b2-11ea-865a-04d2e4b5789f.jpg)

**Comment by jefersonralmeida** [comment]
@joaoaugustogrobe / @edsonsilvajr , precisamos incluir rolagem nesse modal..., acredito que seja simples.
