### ISSUE TITLE
Instrução de uso

### ISSUE THREAD

**Issue by hernanicruz** [jefersonralmeida/sospandemia#84]
Amigos que acessaram a ferramenta, reportaram a necessidade de colocar um Splash com informações sobre o uso da ferramenta.

**Comment by jefersonralmeida** [comment]
Isso estava previsto para entrar no texto do quem somos, mas foi ignorado.

**Comment by hernanicruz** [comment]
Atualização das instruções para os procedimentos da entidade realizar seu cadastro
