### ISSUE TITLE
Erro no campo quantidade

### ISSUE THREAD

**Issue by hernanicruz** [jefersonralmeida/sospandemia#85]
# problema
Ao cadastrar quantidades grades aparece uma seguinte msg:
Ele não aceita o quantitativo 10.000 unidades.
Erro ao.adicionar a demanda

**Comment by jefersonralmeida** [comment]
Testei até com um trilhão e funciona. O problema é o ponto. Vou passar esse erro pro @joaoaugustogrobe e para o @edsonsilvajr , para que eles possam substituir o campo por um campo numérico que só aceite inteiros (e não aceite pontos). É bom também colocar um texto de ajuda no label, do tipo: "apenas dígitos", ou algo assim.

@hernanicruz , responda o chamado pedindo para incluir sem o ponto.

**Comment by joaoaugustogrobe** [comment]
Corrigido em 82fe22be6dba449ad3033b87d7ce0ca702997d5c
Centralização de todas as regras de validação em um componente Mixin. 
Regra para validação agora esta utilizando uma expressão regular para identificar números, e diferenciando erros para carácteres inválidos e valores negativos.
