### ISSUE TITLE
Erros genéricos na criação de entidades

### ISSUE THREAD

**Issue by hernanicruz** [jefersonralmeida/sospandemia#90]
# Problema
Ao cadastrar uma entidade, se o usuário por exemplo, errar o cnpj, não retornamos o erro para que ele verifique que não está correto. Apenas apresentamos uma mensagem que não foi possível cadastrar a entidade.

# Solução
Consultar se existe o cnpj informado antes e exibir o erro associado a duplicidade.

**Comment by joaoaugustogrobe** [comment]
Resolvido em ae6a9e9772f543cd37ccfdf6b8e055573cbf0a60
Criado método para a validação pela resposta retornada pelo backend.
